set(XXX_INCLUDE_DIRS ${CMAKE_CURRENT_LIST_DIR}/include)
set(XXX_LIBRARY_DIRS ${CMAKE_CURRENT_LIST_DIR}/lib)
set(XXX_LIBRARIES ${CMAKE_CURRENT_LIST_DIR}/XXX.lib)
set(XXX_DEFINITIONS -DXXX)

mark_as_advanced(XXX_DIR)